export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  VERIFY_EMAIL: '/verify-email',
  DASHBOARD: '/dashboard',
  RESUMES: '/resumes',
  RESUME_BUILDER: '/resumes/builder/:id',
  PORTFOLIOS: '/portfolios',
  PORTFOLIO_BUILDER: '/portfolios/builder/:id',
  PUBLIC_PORTFOLIO: '/p/:slug',
  AI_HUB: '/ai-hub',
  BRAND_STUDIO: '/brand-studio',
  CONTENT_STUDIO: '/content-studio',
  JOBS: '/jobs',
  JOB_WORKSPACE: '/jobs/:id',
  CAREER_ANALYTICS: '/jobs/analytics',
  SETTINGS: '/settings',
  ADMIN: '/admin',
  RECRUITER_DASHBOARD: '/recruiter/dashboard',
  RECRUITER_COMPANY: '/recruiter/company',
  RECRUITER_JOBS: '/recruiter/jobs',
  RECRUITER_SEARCH: '/recruiter/search',
  PRIVACY_POLICY: '/privacy-policy',
  TERMS_OF_SERVICE: '/terms-of-service',
} as const
